insert into MOVIES (id, searchtype, expression, errorMessage) values (1, 'Title', 'inception 2010', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (2, 'Series', 'Fuck Up', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (3, 'All', 'Gojoe: Spirit War Chronicle (Gojo reisenki: Gojoe)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (4, 'Keyword', 'Hairdresser''s Husband, The (Le mari de la coiffeuse)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (5, 'Keyword', 'Thrill of It All, The', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (6, 'Series', 'Humpday', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (7, 'Series', 'Two Bits', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (8, 'Title', 'Jackass Presents: Bad Grandpa .5', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (9, 'Episode', 'God''s Pocket', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (10, 'Series', 'Odette Toulemonde', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (11, 'All', 'Living Will...', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (12, 'Company', 'Will It Snow For Christmas? (Y''aura-t-il de la neige à Noël?)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (13, 'Title', 'First Strike (Police Story 4: First Strike) (Ging chaat goo si 4: Ji gaan daan yam mo)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (14, 'Series', 'Die Is Cast, The (La suerte está echada)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (15, 'Name', 'Filly Brown', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (16, 'Movie', 'Night and Day (Bam gua nat)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (17, 'Keyword', 'Dangerous Man, A', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (18, 'All', 'Lovers & Leavers (Kuutamolla)', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (19, 'All', 'Head', '');
insert into MOVIES (id, searchtype, expression, errorMessage) values (20, 'Title', 'Superman/Shazam!: The Return of Black Adam (DC Showcase Original Shorts Collection)', '');